import 'package:journal/utils/uuid_maker.dart';

class JournalEntry {
  // Text content reflecting what user is grateful for today
  final String gratitudeText;

  // Text content describing highlight of user's day
  final String highlightText;

  // Unique identifier for journal entry, generated by UUIDMaker
  final UUIDString uuid;

  // TImestamp when entry was last updated
  final DateTime updatedAt;

  // Timestamp when entry was created
  final DateTime createdAt;

  // Creates a new journal entry w gratitude and highlight texts
  factory JournalEntry(
      {gratitudeText = '',
      highlightText = '',
      required DateTime createdAt,
      required DateTime updatedAt,
      required UUIDString uuid}) {
    final when = DateTime.now();
    return JournalEntry.withTextUUIDUpdatedAtCreatedAt(
        gratitudeText: gratitudeText,
        highlightText: highlightText,
        uuid: UUIDMaker.generateUUID(),
        updatedAt: when,
        createdAt: when);
  }

  // Initializes a JournalEntry with all the properties
  JournalEntry.withTextUUIDUpdatedAtCreatedAt(
      {required this.gratitudeText,
      required this.highlightText,
      required this.uuid,
      required this.updatedAt,
      required this.createdAt});

  // Updates existing JournalEntry with new gratitude or highlight texts
  JournalEntry.withUpdatedText(JournalEntry entry,
      {String newGratitudeText = '', String newHighlightText = ''})
      : uuid = entry.uuid,
        createdAt = entry.createdAt,
        updatedAt = DateTime.now(),
        gratitudeText =
            newGratitudeText.isEmpty ? entry.gratitudeText : newGratitudeText,
        highlightText =
            newHighlightText.isEmpty ? entry.highlightText : newHighlightText;
}
